version: "3.8"

services:

  # ---------------- ZOOKEEPER ----------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ---------------- KAFKA ----------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Internal + external listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # ---------------- MYSQL (ORDERS) ----------------
  mysql-orders:
    image: mysql:8.0
    container_name: mysql-orders
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    volumes:
      - mysql_orders_data:/var/lib/mysql

  # ---------------- MYSQL (PAYMENTS) ----------------
  mysql-payments:
    image: mysql:8.0
    container_name: mysql-payments
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
    volumes:
      - mysql_payments_data:/var/lib/mysql

  # ---------------- ORDER SERVICE ----------------
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mysql-orders
      - payment-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-orders:3306/orders
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      PAYMENT_SERVICE_URL: http://payment-service:8082

  # ---------------- PAYMENT SERVICE ----------------
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mysql-payments
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-payments:3306/payments
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

# ---------------- VOLUMES ----------------
volumes:
  mysql_orders_data:
  mysql_payments_data: